// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// read_sparse_svm
List read_sparse_svm(std::string path, int min_col_index, bool return_tranpose);
RcppExport SEXP _readsvm_read_sparse_svm(SEXP pathSEXP, SEXP min_col_indexSEXP, SEXP return_tranposeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< int >::type min_col_index(min_col_indexSEXP);
    Rcpp::traits::input_parameter< bool >::type return_tranpose(return_tranposeSEXP);
    rcpp_result_gen = Rcpp::wrap(read_sparse_svm(path, min_col_index, return_tranpose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_readsvm_read_sparse_svm", (DL_FUNC) &_readsvm_read_sparse_svm, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_readsvm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
