# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Read SVM Light sparse data
#' @description Convenience function to read svm light data format
#' @param path address of file saved in \code{.svm} format
#' @param zero_indexing integer indicating if stored data indicated columns indexing starting from 0 or 1
#' @param zero_one_response the default output for the response variable is 1, -1; set to true to change to 1, 0.
#' @param transpose logical indicating if feature matrix should be returned transposed (see details).
#' @param nfeatures optional non negative integer indicating the total number of features in the matrix, if the value is zero (by default)
#' the number of features is taken from the observed data. Use when the number of features is known and you want to run data in batches.
#' @return an object of class dgCMatrix from the Matrix package
#' @details Most sparse matrix libraries have better support for column-compressed sparse data format while algorithms 
#' require to read information by row. The default return_transpose = true to make this easier.
#' @export
read_svm <- function(path, zero_indexing = TRUE, zero_one_response = FALSE, transpose = TRUE, nfeatures = 0L) {
    .Call(`_readsvm_read_svm`, path, zero_indexing, zero_one_response, transpose, nfeatures)
}

