# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Read SVM Light into Sparse
#' @description Convenience function to read svm light data format
#' @param path File : to data in .svm format
#' @param min_col_index : integer indicating if stored data indicated columns indexing starting from 0 or 1
#' @param return_transpose : logical indicating if feature matrix should be returned transposed (see details)
#' @return an object of class dgCMatrix from the Matrix package 
#' @details Most sparse matrix libraries have better support for column-compressed sparse data format. So it is recommended to use return_transpose = true for efficiency
#' @export
read_sparse_svm <- function(path, min_col_index = 1L, return_tranpose = FALSE) {
    .Call(`_readsvm_read_sparse_svm`, path, min_col_index, return_tranpose)
}

